# Generated by Django 2.2.15 on 2020-08-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='IpAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='MacAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=20)),
                ('vendor', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='DHCP assigned')),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.IpAddr')),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.MacAddr')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.HostName')),
            ],
        ),
    ]
