# Generated by Django 4.0.2 on 2023-03-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macaddr',
            name='label',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
