# Generated by Django 2.2.15 on 2020-08-19 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hosts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=128)),
                ('start', models.DateTimeField(verbose_name='DNS query')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.IpAddr')),
            ],
        ),
    ]
